### ISSUE TITLE
Multiple people can purchase at same price

### ISSUE THREAD

**Issue by LotCooler** [PizzaDAO/website#12]
I opened 2 windows in different browsers and clicked buy at same time (within a half a second or so.....so it was not super fast...i suspect it only needs to be fast enough to not update price on 2nd browser).... It allowed both transactions to occur.  You can see the 2nd purchase I even waited 1.5 minutes to commit the transaction.

The 2 different browsers were firefox and edge on windows.  
[https://rinkeby.etherscan.io/tx/0x1b13888050cedbb6c53b5a1699fb03787c0032af57b9b4734a00503d79269f3f](https://rinkeby.etherscan.io/tx/0x1b13888050cedbb6c53b5a1699fb03787c0032af57b9b4734a00503d79269f3f)  
https://rinkeby.etherscan.io/tx/0xb09d488c37f8777d65ba8ef2736b91eda5b242ca3bd67ab25fe8533ae38f5128

**Comment by 0xSchwifty** [comment]
This is not an issue, consequent txs might be processed with the same value (1.2x current price) but the value returned after purchase differs between them

**Comment by LotCooler** [comment]
My only comments on that would be....  
1) I would say there should be a better warning about paying more than you think you are paying.  Now that you are telling me that you have something that sounds like a "buffer" of 20% extra, i see that is what the message above the buy button says.  But it is not clear at all that is what is meant by that message.  Everyone in my household reads that message as  "you will be charged 20% more, and that 20% will be returned back to you".   That message needs reworking to be more clear that possibly none of the 20% will be returned.  If orders come in at a very high speed, then there is a chance that there will be people where this 20% addition will be completely used and they will have nothing returned.  It may need to be split up into a detail section to be more clear.  Maybe something similar to this...

Above the buy button it says...

You will be charged 20%  more than current price. See note below.

  
Then, below the Sell/Redeem buttons, have a smaller note reading....

Due to extreme speed of incoming orders and delays in browser price refreshing, you will be charged 20% more than the currently shown price.  Some of this additional 20% may be included in your final price you pay depending on the timing of all orders received.  After final calculations are made, if not all of the 20% additional is used in your final price, then any remaining will be returned to your original address.

  
2) During the feeding frenzy of purchasing these, it will probably be likely that many people will all click purchase right at the beginning at the lower price and their window will allow them to purchase at the 1.2X price they had when they clicked the BUY button.  I don't know if there is a reasonable way around this, or if it will be that drastic.  But there is a risk that many people will get pricing at 1.2x the floor price because of this.  Not sure if that will be very widespread or not, but just figured I would call it out.
