### ISSUE TITLE
Unable to connect metamask wallet (windows desktop, chrome, rinkby network) to test site

### ISSUE THREAD

**Issue by ccdisc** [PizzaDAO/website#4]
Error per Kimchi Boss:

(index):269 Uncaught TypeError: web3.eth.Contract is not a constructor
    at startApp ((index):269)
    at initWeb3 ((index):294)
    at onLoadHandler ((index):317)

**Comment by 0xSchwifty** [comment]
@ccdisc can you try again? If it persists please share the logs and your chrome version

**Comment by kPatch** [comment]
**Edge case**: Web3 conflict for users that have MetaMask, along with ONE Wallet and/or Math Wallet. Either of those wallets injects and older version of Web3. Debugging further for a few more mins.

**Comment by kPatch** [comment]
ONE wallet web3 issue. 
It overrides the MetaMask injected Web3, with an older one. Keep this in mind, in case we have any users reporting this issue.
