### ISSUE TITLE
"Buy" button moves so you can't click (only when you click near top)

### ISSUE THREAD

**Issue by LotCooler** [PizzaDAO/website#7]
When you click the "buy" button, it shifts down on the screen.  If you click too high on the button, the button will shift down far enough so your mouse is no longer on the button.  When you release, it does not trigger the mouse click even correctly (the button only received a mouse-down event, and not a mouse-up event....so the "mouse-click" even was also not triggered).

Even if you do not fix this for Go Live, the issue occurs on the other buttons below it (Sell/Redeem) also, so this issue should be moved to later date to fix those before they become clickable (May).

Tested with same result on Firefox and Edge on windows

**Comment by 0xSchwifty** [comment]
Should be fixed now
